import { ModuleConfig } from "@/types/crud";
import { formatDate, formatRef, formatValue, getRefId } from "@/utils/format-record";

export const moduleConfigs = {
  patients: {
    key: "patients",
    title: "Patient Management",
    eyebrow: "Patient records",
    listTitle: "Patients",
    createTitle: "Add patient",
    editTitle: "Edit patient",
    detailTitle: "Patient profile",
    basePath: "/patients",
    attachmentLabel: "Patient document",
    fields: [
      { key: "fullName", label: "Full name", required: true },
      {
        key: "gender",
        label: "Gender",
        required: true,
        type: "select",
        options: [
          { label: "Male", value: "male" },
          { label: "Female", value: "female" },
          { label: "Other", value: "other" },
        ],
      },
      { key: "phone", label: "Phone", required: true },
      { key: "dateOfBirth", label: "Date of birth", required: true, type: "date" },
      { key: "nic", label: "NIC" },
      { key: "email", label: "Email" },
      { key: "address", label: "Address", required: true, type: "multiline" },
      {
        key: "status",
        label: "Status",
        type: "select",
        visibleIn: ["edit"],
        options: [
          { label: "Active", value: "active" },
          { label: "Inactive", value: "inactive" },
        ],
      },
    ],
    defaultValues: { fullName: "", gender: "female", phone: "", dateOfBirth: "", nic: "", email: "", address: "", status: "active" },
    getCardTitle: (record) => formatValue(record.fullName),
    getCardSubtitle: (record) => `${formatValue(record.referenceId)} | ${formatValue(record.phone)} | ${formatValue(record.status)}`,
    getDetailRows: (record) => [
      { label: "Full name", value: formatValue(record.fullName) },
      { label: "Age", value: formatValue(record.age) },
      { label: "Gender", value: formatValue(record.gender) },
      { label: "Phone", value: formatValue(record.phone) },
      { label: "Date of birth", value: formatDate(record.dateOfBirth) },
      { label: "NIC", value: formatValue(record.nic) },
      { label: "Email", value: formatValue(record.email) },
      { label: "Address", value: formatValue(record.address) },
      { label: "Status", value: formatValue(record.status) },
    ],
  },
  doctors: {
    key: "doctors",
    title: "Doctor Management",
    eyebrow: "Doctor records",
    listTitle: "Doctors",
    createTitle: "Add doctor",
    editTitle: "Edit doctor",
    detailTitle: "Doctor profile",
    basePath: "/doctors",
    attachmentLabel: "Doctor profile image/document",
    attachmentUrlKey: "profileImageUrl",
    attachmentNameKey: "profileImageName",
    fields: [
      { key: "fullName", label: "Full name", required: true },
      { key: "specialization", label: "Specialization", required: true },
      { key: "phone", label: "Phone", required: true },
      { key: "email", label: "Email" },
      { key: "room", label: "Room" },
      { key: "experienceYears", label: "Experience years", type: "number" },
      { key: "sessionFee", label: "Session fee", type: "number" },
      { key: "availabilityText", label: "Availability", type: "multiline", placeholder: "mon 08:00-14:00, wed 08:00-14:00" },
      {
        key: "availabilityStatus",
        label: "Availability",
        type: "select",
        options: [
          { label: "Available", value: "available" },
          { label: "Unavailable", value: "unavailable" },
          { label: "On leave", value: "on_leave" },
        ],
      },
      {
        key: "status",
        label: "Status",
        type: "select",
        options: [
          { label: "Active", value: "active" },
          { label: "Inactive", value: "inactive" },
        ],
      },
    ],
    defaultValues: {
      fullName: "",
      specialization: "",
      phone: "",
      email: "",
      room: "",
      experienceYears: "",
      sessionFee: "",
      availabilityText: "",
      availabilityStatus: "available",
      status: "active",
    },
    getCardTitle: (record) => formatValue(record.fullName),
    getCardSubtitle: (record) => `${formatValue(record.referenceId)} | ${formatValue(record.specialization)} | ${formatValue(record.availabilityStatus)}`,
    getDetailRows: (record) => [
      { label: "Full name", value: formatValue(record.fullName) },
      { label: "Specialization", value: formatValue(record.specialization) },
      { label: "Phone", value: formatValue(record.phone) },
      { label: "Email", value: formatValue(record.email) },
      { label: "Room", value: formatValue(record.room) },
      { label: "Experience years", value: formatValue(record.experienceYears) },
      { label: "Session fee", value: formatValue(record.sessionFee) },
      {
        label: "Availability",
        value: Array.isArray(record.availability)
          ? record.availability
              .map((item: any) => `${item.dayOfWeek} ${item.startTime}-${item.endTime}`)
              .join(", ")
          : "Not set",
      },
      { label: "Availability status", value: formatValue(record.availabilityStatus) },
      { label: "Status", value: formatValue(record.status) },
    ],
  },
  appointments: {
    key: "appointments",
    title: "Appointment Management",
    eyebrow: "Visit workflow",
    listTitle: "Appointments",
    createTitle: "Book appointment",
    editTitle: "Edit appointment",
    detailTitle: "Appointment details",
    basePath: "/appointments",
    attachmentLabel: "Appointment document",
    fields: [
      { key: "patientId", label: "Patient", required: true, type: "reference", reference: "patients" },
      { key: "doctorId", label: "Doctor", required: true, type: "reference", reference: "doctors" },
      { key: "appointmentDate", label: "Appointment date", required: true, type: "date", placeholder: "YYYY-MM-DD" },
      { key: "timeSlot", label: "Time slot", required: true, type: "time", placeholder: "09:30 AM" },
      { key: "reason", label: "Reason", required: true, type: "multiline" },
      {
        key: "status",
        label: "Status",
        type: "select",
        options: [
          { label: "Booked", value: "booked" },
          { label: "Rescheduled", value: "rescheduled" },
          { label: "Pending", value: "pending" },
          { label: "Confirmed", value: "confirmed" },
          { label: "Rejected", value: "rejected" },
          { label: "Completed", value: "completed" },
          { label: "Cancelled", value: "cancelled" },
        ],
      },
    ],
    defaultValues: { patientId: "", doctorId: "", appointmentDate: "", timeSlot: "", reason: "", status: "booked" },
    getCardTitle: (record) => formatRef(record.patientId),
    getCardSubtitle: (record) => `${formatValue(record.referenceId)} | ${formatRef(record.doctorId)} | ${formatDate(record.appointmentDate)} ${formatValue(record.timeSlot)}`,
    getDetailRows: (record) => [
      { label: "Patient", value: formatRef(record.patientId) },
      { label: "Patient ID", value: getRefId(record.patientId) || "Not set" },
      { label: "Doctor", value: formatRef(record.doctorId) },
      { label: "Doctor ID", value: getRefId(record.doctorId) || "Not set" },
      { label: "Date", value: formatDate(record.appointmentDate) },
      { label: "Time slot", value: formatValue(record.timeSlot) },
      { label: "Reason", value: formatValue(record.reason) },
      { label: "Status", value: formatValue(record.status) },
    ],
  },
  billing: {
    key: "billing",
    title: "Billing Management",
    eyebrow: "Payments",
    listTitle: "Bills",
    createTitle: "Create bill",
    editTitle: "Edit bill",
    detailTitle: "Bill details",
    basePath: "/billing",
    attachmentLabel: "Receipt / invoice",
    attachmentUrlKey: "receiptUrl",
    attachmentNameKey: "receiptName",
    fields: [
      { key: "appointmentId", label: "Appointment", required: true, type: "reference", reference: "appointments" },
      { key: "patientId", label: "Patient", required: true, type: "reference", reference: "patients", readOnly: true },
      { key: "amount", label: "Amount", required: true, type: "number" },
      { key: "billDate", label: "Bill date", required: true, type: "date", placeholder: "YYYY-MM-DD" },
      {
        key: "paymentMethod",
        label: "Payment method",
        type: "select",
        options: [
          { label: "Cash", value: "cash" },
          { label: "Card", value: "card" },
          { label: "Online", value: "online" },
          { label: "Insurance", value: "insurance" },
        ],
      },
      {
        key: "paymentStatus",
        label: "Payment status",
        type: "select",
        options: [
          { label: "Pending", value: "pending" },
          { label: "Paid", value: "paid" },
          { label: "Cancelled", value: "cancelled" },
        ],
      },
      { key: "notes", label: "Notes", type: "multiline" },
    ],
    defaultValues: {
      patientId: "",
      appointmentId: "",
      amount: "",
      billDate: "",
      paymentMethod: "cash",
      paymentStatus: "pending",
      notes: "",
    },
    getCardTitle: (record) => `Rs. ${formatValue(record.amount)}`,
    getCardSubtitle: (record) => `${formatValue(record.referenceId)} | ${formatRef(record.patientId)} | ${formatValue(record.paymentStatus)}`,
    getDetailRows: (record) => [
      { label: "Patient", value: formatRef(record.patientId) },
      { label: "Patient ID", value: getRefId(record.patientId) || "Not set" },
      { label: "Appointment", value: formatRef(record.appointmentId) },
      { label: "Appointment ID", value: getRefId(record.appointmentId) || "Not set" },
      { label: "Amount", value: `Rs. ${formatValue(record.amount)}` },
      { label: "Bill date", value: formatDate(record.billDate) },
      { label: "Payment method", value: formatValue(record.paymentMethod) },
      { label: "Payment status", value: formatValue(record.paymentStatus) },
      { label: "Notes", value: formatValue(record.notes) },
    ],
  },
  medicalRecords: {
    key: "medical-records",
    title: "Medical Records",
    eyebrow: "Clinical history",
    listTitle: "Medical records",
    createTitle: "Create record",
    editTitle: "Edit record",
    detailTitle: "Medical record details",
    basePath: "/medical-records",
    attachmentLabel: "Medical report/document",
    fields: [
      { key: "appointmentId", label: "Appointment", required: true, type: "reference", reference: "appointments" },
      { key: "patientId", label: "Patient", required: true, type: "reference", reference: "patients", readOnly: true },
      { key: "doctorId", label: "Doctor", required: true, type: "reference", reference: "doctors", readOnly: true },
      { key: "visitSummary", label: "Visit summary", required: true, type: "multiline" },
      { key: "diagnosis", label: "Diagnosis", required: true },
      { key: "treatmentNotes", label: "Treatment notes", required: true, type: "multiline" },
      { key: "recordDate", label: "Record date", required: true, type: "date", placeholder: "YYYY-MM-DD" },
      {
        key: "status",
        label: "Status",
        type: "select",
        options: [
          { label: "Active", value: "active" },
          { label: "Archived", value: "archived" },
        ],
      },
    ],
    defaultValues: {
      patientId: "",
      doctorId: "",
      appointmentId: "",
      visitSummary: "",
      diagnosis: "",
      treatmentNotes: "",
      recordDate: "",
      status: "active",
    },
    getCardTitle: (record) => formatValue(record.diagnosis),
    getCardSubtitle: (record) => `${formatValue(record.referenceId)} | ${formatRef(record.patientId)} | ${formatDate(record.recordDate)}`,
    getDetailRows: (record) => [
      { label: "Patient", value: formatRef(record.patientId) },
      { label: "Patient ID", value: getRefId(record.patientId) || "Not set" },
      { label: "Doctor", value: formatRef(record.doctorId) },
      { label: "Doctor ID", value: getRefId(record.doctorId) || "Not set" },
      { label: "Appointment", value: formatRef(record.appointmentId) },
      { label: "Appointment ID", value: getRefId(record.appointmentId) || "Not set" },
      { label: "Visit summary", value: formatValue(record.visitSummary) },
      { label: "Diagnosis", value: formatValue(record.diagnosis) },
      { label: "Treatment notes", value: formatValue(record.treatmentNotes) },
      { label: "Record date", value: formatDate(record.recordDate) },
      { label: "Status", value: formatValue(record.status) },
    ],
  },
} satisfies Record<string, ModuleConfig>;
